services:
  ia_gps:
    hostname:         ia_gps.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_gps:latest
        -           ia_gps:latest
        - innovanon/ia_gps
        -           ia_gps
    restart:          no
    logging:
      driver:         syslog   
